version: 0.3.2.{build}

install:
  - ps: Install-Product node 5
  - npm install -g grunt-cli
  - npm install

build_script:
  - grunt default

test_script:
  - grunt test

artifacts:
  - path: tracekit*.*
