version: 0.2.0.{build}

environment:
  nodejs_version: "0.10"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g grunt-cli
  - npm install

before_build:
  - appveyor DownloadFile "http://dl.google.com/closure-compiler/compiler-latest.zip" -FileName compiler-latest.zip
  - 7z e compiler-latest.zip closure

build_script:
  - grunt default

test_script:
  - grunt test

artifacts:
  - path: tracekit*.*
